# Generated by Django 6.0.2 on 2026-08-18 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField()),
                ('factor_breakdown', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_assessments', to='incidents.civicincident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
