# Generated by Django 6.0.2 on 2026-08-18 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('detected_objects', models.JSONField(default=list)),
                ('confidence', models.FloatField()),
                ('raw_response', models.JSONField(default=dict)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='evidence.evidence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
