# Generated by Django 6.0.2 on 2026-08-18 03:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('source', models.CharField(choices=[('GPS', 'Device GPS Sensor'), ('MANUAL', 'Manual Address Picker')], default='GPS', max_length=10)),
                ('captured_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('area_type', models.CharField(choices=[('STATE', 'State'), ('DISTRICT', 'District'), ('ULB', 'Urban Local Body (Nigam/Municipality)'), ('WARD', 'Ward')], db_index=True, max_length=10)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geography.administrativearea')),
            ],
            options={
                'unique_together': {('parent', 'name', 'area_type')},
            },
        ),
    ]
