# Generated by Django 6.0.2 on 2026-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativearea',
            name='area_type',
            field=models.CharField(choices=[('STATE', 'State'), ('DISTRICT', 'District'), ('SUBDISTRICT', 'Subdistrict / Tehsil'), ('BLOCK', 'Development Block'), ('PANCHAYAT', 'Gram Panchayat'), ('VILLAGE', 'Village'), ('ULB_CORP', 'Municipal Corporation'), ('ULB_MUNI', 'Municipality'), ('ULB_NAC', 'NAC / Town'), ('WARD', 'Ward')], db_index=True, max_length=20),
        ),
    ]
