# Generated by Django 6.0.2 on 2026-08-18 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(max_length=512)),
                ('media_type', models.CharField(max_length=100)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed / Upload Complete'), ('failed', 'Upload Failed')], default='pending', max_length=20)),
                ('checksum', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
