# Generated by Django 6.0.2 on 2026-08-18 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0001_initial'),
        ('evidence', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='reported', max_length=20)),
                ('citizen_report_count', models.PositiveIntegerField(default=1)),
                ('first_reported_at', models.DateTimeField(db_index=True)),
                ('last_reported_at', models.DateTimeField(db_index=True)),
                ('administrative_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geography.administrativearea')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='authorities.authority')),
                ('representative_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representative_incidents', to='geography.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='evidence.evidence')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='geography.location')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='incidents.civicincident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
