# Generated by Django 6.1 on 2026-08-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
        ('geography', '0002_alter_administrativearea_area_type'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicincident',
            name='administrative_area',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geography.administrativearea'),
        ),
        migrations.AlterField(
            model_name='civicincident',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='civicincident',
            name='last_reported_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='civicincident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20),
        ),
        migrations.AddIndex(
            model_name='civicincident',
            index=models.Index(fields=['administrative_area', 'category', 'status', 'last_reported_at'], name='incidents_c_adminis_716981_idx'),
        ),
    ]
