# Generated by Django 6.0.2 on 2026-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='contact_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('verified_only', 'Verified Only')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='location_sharing',
            field=models.CharField(choices=[('always', 'Always'), ('while_reporting', 'While Reporting'), ('never', 'Never')], default='always', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=15),
        ),
    ]
