# Generated by Django 6.0.2 on 2026-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpreferences_contact_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Authority Officer'), ('farmer', 'Farmer')], default='citizen', max_length=15),
        ),
    ]
