# Generated by Django 6.0.2 on 2026-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_transferred', 'Sold / Transferred'), ('completed_donated', 'Completed / Donated'), ('inactive_expired', 'Inactive / Expired')], db_index=True, default='active', max_length=30),
        ),
    ]
